---
- name: Install Web Server Packages
  hosts: web
  become: true

  tasks:
  - name: Update Apt
    apt:
      update_cache: true
  - name: Install Apache2
    apt:
      name: apache2
      state: present
  - name: Install ghostscript
    apt:
      name: ghostscript
      state: present
  - name:  Install libapache2-mod-php
    apt:
      name: libapache2-mod-php
      state: present
  - name:  Install mysql-client
    apt:
      name: mysql-client
      state: present
  - name:  Install php 
    apt:
      name: php 
      state: present
  - name:  Install php-bcmath
    apt:
      name: php-bcmath
      state: present
  - name:  Install php-curl
    apt:
      name: php-curl
      state: present
  - name:  Install php-imagick
    apt:
      name: php-imagick
      state: present
  - name:  Install php-intl
    apt:
      name: php-intl
      state: present
  - name:  Install php-json
    apt:
      name: php-json
      state: present
  - name: Install php-mbstring 
    apt:
      name: php-mbstring
      state: present
  - name: Install php-mysql
    apt:
      name: php-mysql
      state: present
  - name: Install php-xml
    apt:
      name: php-xml
      state: present
  - name: Install php-zip
    apt:
      name: php-zip
      state: present
  - name: Install mariadb-client
    apt:
      name: mariadb-client
      state: present

- name: Install WordPress
  hosts: web
  become: true

  tasks:
  - name: Remove index.html
    file:
      path: /var/www/html/index.html
      state: absent
  - name: Install unzip
    apt:
      name: unzip
      state: present
  - name: Download WordPress
    get_url:
      url: https://wordpress.org/wordpress-6.1.1.tar.gz
      dest: /home/vagrant
  - name: UnArchiving WordPress.tar.gz
    command:
      cmd: tar xf /home/vagrant/wordpress-6.1.1.tar.gz -C /var/www/html --strip 1
  - name: Delete wordpress.tar.gz
    file:
      path: /home/vagrant/wordpress-6.1.1.tar.gz
      state: absent
  - name: Create wp-config.php
    copy:
      src: /home/vagrant/wp-config.php
      dest: /var/www/html


- name: Finish Tasks
  hosts: web
  become: true

  tasks:
  - name: Change www-data Group
    user:
      name: www-data
      groups: ubuntu
      append: true
  - name: Change Directory Right
    file:
      path: /var/www/html
      owner: www-data
      group: www-data
      recurse: true
  - name: Change misc directories
    command:
      cmd: find /var/www -type d -exec sudo chmod 2775 {} \;
  - name: Change misc files
    command:
      cmd: find /var/www -type f -exec sudo chmod 0664 {} \;
  - name: Restart Apache2
    service:
      name: apache2
      state: restarted

- name: Install MariaDB Server
  hosts: db
  become: true

  tasks:
  - name: Update APT
    apt:
      update_cache: true
  - name: Install MariaDB
    apt:
      name: mariadb-server
      state: present
...
